-- ============================================================
-- PLA MINICHECK - CONSOLIDATED SQL
-- Generated: 2026-08-12
-- ============================================================
-- TWO single-block queries:
--   Query 1 → connect to SYSTEMDB, paste and run
--   Query 2 → connect to B4P tenant, paste and run
-- Each returns (CHECK_NAME, RESULT) rows.
-- ============================================================


-- ============================================================
-- QUERY 1 — SYSTEMDB
-- ============================================================
SELECT 'Cloud'                     AS CHECK_NAME,
       MAX(CASE WHEN KEY = 'cloud_provider'      THEN VALUE END)              AS RESULT
FROM SYS.M_HOST_INFORMATION WHERE HOST = (SELECT HOST FROM SYS.M_DATABASE)
UNION ALL
SELECT 'Hosttype',
       MAX(CASE WHEN KEY = 'cloud_instance_type' THEN VALUE END)
FROM SYS.M_HOST_INFORMATION WHERE HOST = (SELECT HOST FROM SYS.M_DATABASE)
UNION ALL
SELECT 'CPU_PHYS',
       TO_NVARCHAR(MAX(CASE WHEN KEY = 'cpu_cores'   THEN TO_INTEGER(VALUE) END))
FROM SYS.M_HOST_INFORMATION WHERE HOST = (SELECT HOST FROM SYS.M_DATABASE)
UNION ALL
SELECT 'CPU_LOG',
       TO_NVARCHAR(MAX(CASE WHEN KEY = 'cpu_threads' THEN TO_INTEGER(VALUE) END))
FROM SYS.M_HOST_INFORMATION WHERE HOST = (SELECT HOST FROM SYS.M_DATABASE)
UNION ALL
SELECT 'CPU_SOCK',
       TO_NVARCHAR(MAX(CASE WHEN KEY = 'cpu_sockets' THEN TO_INTEGER(VALUE) END))
FROM SYS.M_HOST_INFORMATION WHERE HOST = (SELECT HOST FROM SYS.M_DATABASE)
UNION ALL
SELECT 'PHYS_MEM',
       TO_NVARCHAR(TO_DECIMAL(MAX(CASE WHEN KEY = 'mem_phys' THEN TO_BIGINT(VALUE) END) / 1073741824, 10, 0))
FROM SYS.M_HOST_INFORMATION WHERE HOST = (SELECT HOST FROM SYS.M_DATABASE)
UNION ALL
SELECT 'SID',            SYSTEM_ID                                              FROM SYS.M_DATABASE
UNION ALL
SELECT 'sidadm',         LOWER(SYSTEM_ID) || 'adm'                             FROM SYS.M_DATABASE
UNION ALL
SELECT 'Instancenumber', SUBSTR(TO_VARCHAR(SQL_PORT), 2, 2)                    FROM SYS.M_DATABASE
UNION ALL
SELECT 'HDB version',    SUBSTR(VERSION, 1, LOCATE(VERSION, '.', 1, 4) - 1)   FROM SYS.M_DATABASE
UNION ALL
SELECT 'MDC',
       CASE WHEN COUNT(*) > 0 THEN 'true' ELSE 'false' END
FROM SYS.M_DATABASES WHERE DATABASE_NAME != 'SYSTEMDB'
UNION ALL
SELECT 'Multinode',
       CASE WHEN COUNT(DISTINCT HOST) > 1 THEN 'true' ELSE 'false' END
FROM SYS.M_LANDSCAPE_HOST_CONFIGURATION
UNION ALL
SELECT 'Installationname', HOST                                                FROM SYS.M_DATABASE
UNION ALL
SELECT 'Virtual Hostname',
       COALESCE((SELECT VALUE FROM SYS.M_HOST_INFORMATION
                 WHERE HOST = D.HOST AND KEY = 'net_virtual_hostnames'), D.HOST)
FROM SYS.M_DATABASE D
UNION ALL
SELECT 'Instance',
       CASE WHEN SUM(CASE WHEN ACTIVE_STATUS != 'YES' THEN 1 ELSE 0 END) = 0
            THEN 'green -> running' ELSE 'red -> stopped' END
FROM SYS.M_SERVICES WHERE SERVICE_NAME = 'indexserver'
UNION ALL
SELECT 'Replication',
       COALESCE(NULLIF(MAX(REPLICATION_MODE), 'NONE'), 'none')
FROM SYS.M_SERVICE_REPLICATION
UNION ALL
SELECT 'Volume Size',
       TO_NVARCHAR(ROUND(SUM(FILE_SIZE) / 1073741824)) || 'G'
FROM SYS.M_VOLUME_FILES WHERE FILE_TYPE = 'DATA'
UNION ALL
SELECT 'CPU spikes 95pct (40d)',
       TO_NVARCHAR(SUM(CASE WHEN CPU >= 95 THEN 1 ELSE 0 END))
FROM _SYS_STATISTICS.HOST_LOAD_HISTORY_HOST
WHERE TIME >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'CPU Average (40d)',
       TO_NVARCHAR(ROUND(AVG(TO_DECIMAL(CPU)), 6))
FROM _SYS_STATISTICS.HOST_LOAD_HISTORY_HOST
WHERE TIME >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'Failed Backups (40d)',
       CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'N' END
FROM SYS.M_BACKUP_CATALOG
WHERE STATE_NAME = 'failed'
  AND SYS_START_TIME >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'Long Running Backups',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_BACKUP_CATALOG
WHERE STATE_NAME = 'running'
  AND SECONDS_BETWEEN(SYS_START_TIME, CURRENT_TIMESTAMP) > 7200
UNION ALL
SELECT 'High Memory Allocators SYSTEMDB >30pct',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_HEAP_MEMORY H
JOIN SYS.M_SERVICES S ON H.HOST = S.HOST AND H.PORT = S.PORT
WHERE S.SERVICE_NAME = 'nameserver'
  AND H.INCLUSIVE_SIZE_IN_USE * 100.0 /
      NULLIF((SELECT SUM(ALLOCATION_LIMIT) FROM SYS.M_SERVICE_MEMORY
              WHERE SERVICE_NAME = 'nameserver'), 0) > 30
UNION ALL
SELECT 'Top 10 Allocators SYSTEMDB',
       STRING_AGG(HOST || '|' || SERVICE_NAME || '|' || CATEGORY || '|'
                  || TO_NVARCHAR(ROUND(INCLUSIVE_SIZE_IN_USE / 1073741824, 3)) || 'GB'
                  || '|' || TO_NVARCHAR(ROUND(EXCLUSIVE_SIZE_IN_USE / 1073741824, 3)) || 'GB',
                  '; ' ORDER BY INCLUSIVE_SIZE_IN_USE DESC)
FROM (
    SELECT TOP 10 H.HOST, S.SERVICE_NAME, H.CATEGORY,
           H.INCLUSIVE_SIZE_IN_USE, H.EXCLUSIVE_SIZE_IN_USE
    FROM SYS.M_HEAP_MEMORY H
    JOIN SYS.M_SERVICES    S ON H.HOST = S.HOST AND H.PORT = S.PORT
    WHERE S.SERVICE_NAME = 'nameserver'
    ORDER BY H.INCLUSIVE_SIZE_IN_USE DESC
) T
UNION ALL
SELECT 'OOM Events SYSTEMDB (40d)',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_OUT_OF_MEMORY_EVENTS
WHERE TIME >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'P1 Alerts SYSTEMDB (40d)',
       TO_NVARCHAR(COUNT(*))
FROM _SYS_STATISTICS.STATISTICS_ALERTS_BASE
WHERE ALERT_RATING = 5
  AND ALERT_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'Tables over 1.5B records SYSTEMDB',
       TO_NVARCHAR(COUNT(*))
FROM (
    SELECT SCHEMA_NAME, TABLE_NAME, SUM(RECORD_COUNT) AS RECORDS
    FROM SYS.M_CS_TABLES
    GROUP BY SCHEMA_NAME, TABLE_NAME
    HAVING SUM(RECORD_COUNT) > 1500000000
    UNION ALL
    SELECT SCHEMA_NAME, TABLE_NAME, RECORD_COUNT
    FROM SYS.M_RS_TABLES WHERE RECORD_COUNT > 1500000000
) T;


-- ============================================================
-- QUERY 2 — B4P TENANT
-- ============================================================
SELECT 'RowStore Size'             AS CHECK_NAME,
       'ALL-' || TO_NVARCHAR(ROUND(SUM(ALLOCATED_SIZE) / 1073741824, 3)) ||
       ',USE-' || TO_NVARCHAR(ROUND(SUM(USED_SIZE)      / 1073741824, 3))    AS RESULT
FROM SYS.M_RS_MEMORY
UNION ALL
SELECT 'ColumnStore Size',
       TO_NVARCHAR(ROUND(SUM(MEMORY_SIZE_IN_TOTAL) / 1073741824, 3))
FROM SYS.M_CS_TABLES
UNION ALL
SELECT 'Indexserver Memory',
       'ALL:' || TO_NVARCHAR(ROUND(SUM(ALLOCATION_LIMIT)       / 1073741824, 3)) ||
       ',USE:' || TO_NVARCHAR(ROUND(SUM(TOTAL_MEMORY_USED_SIZE) / 1073741824, 3))
FROM SYS.M_SERVICE_MEMORY WHERE SERVICE_NAME = 'indexserver'
UNION ALL
SELECT 'Plan Cache HIT Ratio (40d)',
       TO_NVARCHAR(ROUND(AVG(PLAN_CACHE_HIT_RATIO), 6))
FROM _SYS_STATISTICS.HOST_SQL_PLAN_CACHE_OVERVIEW
WHERE SERVER_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'High Memory Allocators B4P >30pct',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_HEAP_MEMORY H
JOIN SYS.M_SERVICES S ON H.HOST = S.HOST AND H.PORT = S.PORT
WHERE S.SERVICE_NAME = 'indexserver'
  AND H.INCLUSIVE_SIZE_IN_USE * 100.0 /
      NULLIF((SELECT SUM(ALLOCATION_LIMIT) FROM SYS.M_SERVICE_MEMORY
              WHERE SERVICE_NAME = 'indexserver'), 0) > 30
UNION ALL
SELECT 'Top 10 Allocators B4P',
       STRING_AGG(HOST || '|' || SERVICE_NAME || '|' || CATEGORY || '|'
                  || TO_NVARCHAR(ROUND(INCLUSIVE_SIZE_IN_USE / 1073741824, 3)) || 'GB'
                  || '|' || TO_NVARCHAR(ROUND(EXCLUSIVE_SIZE_IN_USE / 1073741824, 3)) || 'GB',
                  '; ' ORDER BY INCLUSIVE_SIZE_IN_USE DESC)
FROM (
    SELECT TOP 10 H.HOST, S.SERVICE_NAME, H.CATEGORY,
           H.INCLUSIVE_SIZE_IN_USE, H.EXCLUSIVE_SIZE_IN_USE
    FROM SYS.M_HEAP_MEMORY H
    JOIN SYS.M_SERVICES    S ON H.HOST = S.HOST AND H.PORT = S.PORT
    WHERE S.SERVICE_NAME = 'indexserver'
    ORDER BY H.INCLUSIVE_SIZE_IN_USE DESC
) T
UNION ALL
SELECT 'OOM Events B4P (40d)',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_OUT_OF_MEMORY_EVENTS
WHERE TIME >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'P1 Alerts B4P (40d)',
       TO_NVARCHAR(COUNT(*))
FROM _SYS_STATISTICS.STATISTICS_ALERTS_BASE
WHERE ALERT_RATING = 5
  AND ALERT_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'Alert Details B4P',
       STRING_AGG(
           TO_NVARCHAR(NUM_EVENTS) || ' events | Rating:' || TO_NVARCHAR(ALERT_RATING) ||
           ' | Alert ID:' || TO_NVARCHAR(ALERT_ID) || ' | ' || COALESCE(ALERT_DETAILS, ''),
           '; ' ORDER BY NUM_EVENTS DESC)
FROM (
    SELECT COUNT(*) AS NUM_EVENTS, ALERT_RATING, ALERT_ID,
           MAX(ALERT_DETAILS) AS ALERT_DETAILS
    FROM _SYS_STATISTICS.STATISTICS_ALERTS_BASE
    WHERE ALERT_RATING = 5
      AND ALERT_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
    GROUP BY ALERT_RATING, ALERT_ID
) T
UNION ALL
SELECT 'Blocked Transactions',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_BLOCKED_TRANSACTIONS
UNION ALL
SELECT 'Big Technical Tables',
       TO_NVARCHAR(COUNT(*)) || ' tables | MEM:' ||
       TO_NVARCHAR(ROUND(SUM(MEMORY_SIZE_IN_TOTAL) / 1073741824, 2)) || 'G | DISK:' ||
       TO_NVARCHAR(ROUND(SUM(PERSISTENT_MEMORY_SIZE_IN_TOTAL) / 1073741824, 2)) || 'G'
FROM SYS.M_CS_TABLES
WHERE (SCHEMA_NAME LIKE '_SYS%' OR SCHEMA_NAME LIKE 'SAP%')
  AND MEMORY_SIZE_IN_TOTAL / 1073741824 > 1.0
UNION ALL
SELECT 'Technical Tables List',
       STRING_AGG(
           SCHEMA_NAME || '.' || TABLE_NAME ||
           ' | MEM:'  || TO_NVARCHAR(ROUND(MEMORY_SIZE_IN_TOTAL / 1073741824, 3)) || 'G' ||
           ' | DISK:' || TO_NVARCHAR(ROUND(PERSISTENT_MEMORY_SIZE_IN_TOTAL / 1073741824, 3)) || 'G' ||
           ' | ROWS:' || TO_NVARCHAR(RECORD_COUNT),
           '; ' ORDER BY MEMORY_SIZE_IN_TOTAL DESC)
FROM SYS.M_CS_TABLES
WHERE (SCHEMA_NAME LIKE '_SYS%' OR SCHEMA_NAME LIKE 'SAP%')
  AND MEMORY_SIZE_IN_TOTAL / 1073741824 > 1.0
UNION ALL
SELECT 'Tables over 1.5B records B4P',
       TO_NVARCHAR(COUNT(*))
FROM (
    SELECT SCHEMA_NAME, TABLE_NAME, SUM(RECORD_COUNT) AS RECORDS
    FROM SYS.M_CS_TABLES
    GROUP BY SCHEMA_NAME, TABLE_NAME
    HAVING SUM(RECORD_COUNT) > 1500000000
    UNION ALL
    SELECT SCHEMA_NAME, TABLE_NAME, RECORD_COUNT
    FROM SYS.M_RS_TABLES WHERE RECORD_COUNT > 1500000000
) T;
