-- ============================================================
-- QUERY 2 — B4P TENANT
-- ============================================================
SELECT 'RowStore Size'             AS CHECK_NAME,
       'ALL-' || TO_NVARCHAR(ROUND(SUM(ALLOCATED_SIZE) / 1073741824, 3)) ||
       ',USE-' || TO_NVARCHAR(ROUND(SUM(USED_SIZE)      / 1073741824, 3))    AS RESULT
FROM SYS.M_RS_MEMORY
UNION ALL
SELECT 'ColumnStore Size',
       TO_NVARCHAR(ROUND(SUM(MEMORY_SIZE_IN_TOTAL) / 1073741824, 3))
FROM SYS.M_CS_TABLES
UNION ALL
SELECT 'Indexserver Memory',
       'ALL:' || TO_NVARCHAR(ROUND(SUM(ALLOCATION_LIMIT)       / 1073741824, 3)) ||
       ',USE:' || TO_NVARCHAR(ROUND(SUM(TOTAL_MEMORY_USED_SIZE) / 1073741824, 3))
FROM SYS.M_SERVICE_MEMORY WHERE SERVICE_NAME = 'indexserver'
UNION ALL
SELECT 'Plan Cache HIT Ratio (40d)',
       TO_NVARCHAR(ROUND(AVG(PLAN_CACHE_HIT_RATIO), 6))
FROM _SYS_STATISTICS.HOST_SQL_PLAN_CACHE_OVERVIEW
WHERE SERVER_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'High Memory Allocators B4P >30pct',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_HEAP_MEMORY H
JOIN SYS.M_SERVICES S ON H.HOST = S.HOST AND H.PORT = S.PORT
WHERE S.SERVICE_NAME = 'indexserver'
  AND H.INCLUSIVE_SIZE_IN_USE * 100.0 /
      NULLIF((SELECT SUM(ALLOCATION_LIMIT) FROM SYS.M_SERVICE_MEMORY
              WHERE SERVICE_NAME = 'indexserver'), 0) > 30
UNION ALL
SELECT 'Top 10 Allocators B4P',
       STRING_AGG(HOST || '|' || SERVICE_NAME || '|' || CATEGORY || '|'
                  || TO_NVARCHAR(ROUND(INCLUSIVE_SIZE_IN_USE / 1073741824, 3)) || 'GB'
                  || '|' || TO_NVARCHAR(ROUND(EXCLUSIVE_SIZE_IN_USE / 1073741824, 3)) || 'GB',
                  '; ' ORDER BY INCLUSIVE_SIZE_IN_USE DESC)
FROM (
    SELECT TOP 10 H.HOST, S.SERVICE_NAME, H.CATEGORY,
           H.INCLUSIVE_SIZE_IN_USE, H.EXCLUSIVE_SIZE_IN_USE
    FROM SYS.M_HEAP_MEMORY H
    JOIN SYS.M_SERVICES    S ON H.HOST = S.HOST AND H.PORT = S.PORT
    WHERE S.SERVICE_NAME = 'indexserver'
    ORDER BY H.INCLUSIVE_SIZE_IN_USE DESC
) T
UNION ALL
SELECT 'OOM Events B4P (40d)',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_OUT_OF_MEMORY_EVENTS
WHERE TIME >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'P1 Alerts B4P (40d)',
       TO_NVARCHAR(COUNT(*))
FROM _SYS_STATISTICS.STATISTICS_ALERTS_BASE
WHERE ALERT_RATING = 5
  AND ALERT_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
UNION ALL
SELECT 'Alert Details B4P',
       STRING_AGG(
           TO_NVARCHAR(NUM_EVENTS) || ' events | Rating:' || TO_NVARCHAR(ALERT_RATING) ||
           ' | Alert ID:' || TO_NVARCHAR(ALERT_ID) || ' | ' || COALESCE(ALERT_DETAILS, ''),
           '; ' ORDER BY NUM_EVENTS DESC)
FROM (
    SELECT COUNT(*) AS NUM_EVENTS, ALERT_RATING, ALERT_ID,
           MAX(ALERT_DETAILS) AS ALERT_DETAILS
    FROM _SYS_STATISTICS.STATISTICS_ALERTS_BASE
    WHERE ALERT_RATING = 5
      AND ALERT_TIMESTAMP >= ADD_DAYS(CURRENT_TIMESTAMP, -40)
    GROUP BY ALERT_RATING, ALERT_ID
) T
UNION ALL
SELECT 'Blocked Transactions',
       TO_NVARCHAR(COUNT(*))
FROM SYS.M_BLOCKED_TRANSACTIONS
UNION ALL
SELECT 'Big Technical Tables',
       TO_NVARCHAR(COUNT(*)) || ' tables | MEM:' ||
       TO_NVARCHAR(ROUND(SUM(MEMORY_SIZE_IN_TOTAL) / 1073741824, 2)) || 'G | DISK:' ||
       TO_NVARCHAR(ROUND(SUM(PERSISTENT_MEMORY_SIZE_IN_TOTAL) / 1073741824, 2)) || 'G'
FROM SYS.M_CS_TABLES
WHERE (SCHEMA_NAME LIKE '_SYS%' OR SCHEMA_NAME LIKE 'SAP%')
  AND MEMORY_SIZE_IN_TOTAL / 1073741824 > 1.0
UNION ALL
SELECT 'Technical Tables List',
       STRING_AGG(
           SCHEMA_NAME || '.' || TABLE_NAME ||
           ' | MEM:'  || TO_NVARCHAR(ROUND(MEMORY_SIZE_IN_TOTAL / 1073741824, 3)) || 'G' ||
           ' | DISK:' || TO_NVARCHAR(ROUND(PERSISTENT_MEMORY_SIZE_IN_TOTAL / 1073741824, 3)) || 'G' ||
           ' | ROWS:' || TO_NVARCHAR(RECORD_COUNT),
           '; ' ORDER BY MEMORY_SIZE_IN_TOTAL DESC)
FROM SYS.M_CS_TABLES
WHERE (SCHEMA_NAME LIKE '_SYS%' OR SCHEMA_NAME LIKE 'SAP%')
  AND MEMORY_SIZE_IN_TOTAL / 1073741824 > 1.0
UNION ALL
SELECT 'Tables over 1.5B records B4P',
       TO_NVARCHAR(COUNT(*))
FROM (
    SELECT SCHEMA_NAME, TABLE_NAME, SUM(RECORD_COUNT) AS RECORDS
    FROM SYS.M_CS_TABLES
    GROUP BY SCHEMA_NAME, TABLE_NAME
    HAVING SUM(RECORD_COUNT) > 1500000000
    UNION ALL
    SELECT SCHEMA_NAME, TABLE_NAME, RECORD_COUNT
    FROM SYS.M_RS_TABLES WHERE RECORD_COUNT > 1500000000
) T;
